repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  delete_branch_on_merge: true
branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      restrictions:
        users:
          - rcoops
