repository:
  name: birthdayculator-python
  delete_branch_on_merge: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
branches:
  - name: main
    protection:
      restrictions:
        users:
          - rcoops
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
