repository:
  name: birthdayculator-python
  delete_branch_on_merge: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
branches:
  - name: main
    protection:
      restrictions:
        users: [rcoops]
        teams: []
        apps: []
      enforce_admins: null
      required_status_checks:
        strict: true
        checks:
          - context: CodeQL
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
