default_install_hook_types:
  - pre-push
  - commit-msg
default_stages:
  - push
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--check"

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - "--check"

  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        language: system
        entry: pytest -v --cov=src --cov-fail-under=100 --cov-branch --cov-report term-missing --verbose
        types:
          - python
        pass_filenames: false
        always_run: true
