on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-n-publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
